### ISSUE TITLE
Parse error with AxiRegTC_test_write.vcd

### ISSUE THREAD

**Issue by raczben** [Nic30/pyDigitalWaveTools#6] opened 2020-08-28 19:34 UTC
Cannot parse [AxiRegTC_test_write.vcd][1]

I used the example code:

```python
#!/usr/bin/env python3
import json
import sys
from pyDigitalWaveTools.vcd.parser import VcdParser

if len(sys.argv) > 1:
    fname = sys.argv[1]
else:
    print('Give me a vcd file to parse')
    sys.exit(-1)

with open(fname) as vcd_file:
    vcd = VcdParser()
    vcd.parse(vcd_file)
    data = vcd.scope.toJson()
    print(json.dumps(data, indent=4, sort_keys=True))
```

pyDigitalWaveTools Versions:

 - 0.6 Passes
 - 0.7 Fails
 - 0.8 Fails

[1]: https://github.com/Nic30/pyDigitalWaveTools/blob/master/pyDigitalWaveTools/tests/AxiRegTC_test_write.vcd

**Comment by Nic30** [comment] 2020-08-28 21:36
Ah, I made a mistake while rewrite of lexer. It should be fixed and also at least checked in tests.
Do you know about any other problem? I am asking because if there is not I will publish new pip package revision.

**Comment by Nic30** [comment] 2020-11-02 00:42
@raczben Can you confirm that the issue is fixed?

**Comment by Nic30** [comment] 2020-12-05 14:39
I take it as it was fixed.

**Closed as completed by Nic30** 2020-12-05 14:39 UTC
